<?php

/**Displays the movie gif if it is installed*/
function xstats_displayMovieGif( $gameId ) {
//the movie could be generated by calling http://<host>/extend/moviegif/movie.php?fu=1&spiel=<gameId>
    $filename = '../moviegif/files/moviegif_'.$gameId.'.gif';
    if( file_exists( $filename )) {
        echo '<img src="../extend/xstats/'.$filename.'" class="beveled">';
    }
}

function xstats_displayGraphsAsFlash($gameId,$graphArray,$width,$height,$displayLegend,$statsPerRow,$isThumb) {
    $count = 0;
    foreach( $graphArray as $type) {
        if ( $isThumb == "FALSE" ) {
            echo( '<a id="box_'.$type.'">&nbsp;</a>');
        }
        if ( $isThumb == "TRUE" ) {
            echo( '<a href="#box_'.$type.'">');
        }
        echo( '<iframe frameborder="0" marginwidth="0" marginheight="0" scrolling="no" class="statsFrame" src="graph.php?gameid='.$gameId.'&type='.$type.'&width='.$width.'&height='.$height.'&outputtype=FLASH" height="'.($height+20).'" width="'.($width+20).'"></iframe>');
        if ( $isThumb == "TRUE" ) {
            echo '</a>';
        }
        if ( ($count+1) % $statsPerRow == 0 ) {
            echo '<br />';
        }

        if ( $isThumb == "FALSE" ) {
            echo( '<a href="#top" class="pageTop">Nach oben</a><br /><br />');
        }
        $count++;
    }
}

function xstats_displayGraphsAsImage($gameId,$graphArray,$width,$height,$displayLegend,$statsPerRow,$isThumb) {
    $count = 0;
    echo '<table cellpadding="5" cellspacing="0" border="0" width="100%">';
    foreach($graphArray as $type) {
        $count++;
        if ($count == 1) {
            echo '<tr>';
        }
        echo '<td align="center" width="' . round((100 / $statsPerRow), 0) . '%"><img src="../extend/xstats/graph.php?gameid='.$gameId.'&type='.$type.'&width='.$width.'&height='.$height.'&outputtype=IMAGE&displayLegend='.$displayLegend.'" /></td>';
        if ($count == $statsPerRow) {
            echo '</tr>';
            $count = 0;
        }
    }
    echo '</table>';
}


function xstats_displayTurnList( $gameId ) {
    $query = "SELECT * FROM skrupel_xstats_turntime WHERE gameid={$gameId} ORDER BY turn";
    $result = @mysql_query( $query );
    echo '<table class="shiptable" border="0">';
    echo '<tr><th>Runde</th><th>Datum</th><th>Wartezeit</th></tr>';
    $dateFormat = "j.n.Y H:i:s";
    $lastTurnTime = -1;
    while($row = @mysql_fetch_array($result)) {
        echo( '<tr>');
        //turn
        echo '<td>'.$row['turn'].'</td>';
        //real date
        echo '<td>'.date($dateFormat,$row['turnendtime']).'</td>';
        if( $lastTurnTime == -1 ) {
            echo '<td></td>';
            $lastTurnTime = $row['turnendtime'];
        }else {
            echo '<td>'.xstats_getDateDiff($lastTurnTime, $row['turnendtime']).'</td>';
            $lastTurnTime = $row['turnendtime'];
        }
        echo '</tr>';
    }
    echo '</table>';
}


/**Displays the max wait time between two turns in this game*/
function xstats_displayMaxWaitTime( $gameId ) {
    $query = "SELECT * FROM skrupel_xstats_turntime WHERE gameid={$gameId} ORDER BY turn";
    $result = @mysql_query( $query );
    $lastTurnTime = -1;
    $maxDifference = 0;
    $maxDifferenceTurn = 1;
    $maxDifferenceTurnTime = 0;
    while($row = @mysql_fetch_array($result)) {
    //init -- ignore the first entry
        if( $lastTurnTime == -1 ) {
            $lastTurnTime = $row['turnendtime'];
        }else {            
            if( $row['turnendtime']-$lastTurnTime > $maxDifference ) {
                $maxDifference = $row['turnendtime']-$lastTurnTime;
                $maxDifferenceTurn = $row['turn'];
                $maxDifferenceTurnTime = $row['turnendtime'];                
            }
            $lastTurnTime = $row['turnendtime'];
        }
    }
    $startDate = $maxDifferenceTurnTime-$maxDifference;
    $endDate = $maxDifferenceTurnTime;
    $dateFormat = "j.n.Y H:i:s";
    echo( 'L&auml;ngste Wartezeit im Spiel: <strong>'.xstats_getDateDiff( $startDate, $endDate)).'</strong> in Runde '.$maxDifferenceTurn.' ('.date($dateFormat,$startDate).' bis '.date($dateFormat,$endDate).')';
}

/**Display the diff between two date entries*/
function xstats_getDateDiff( $dateStart, $dateEnd) {
    $dateDiff = $dateEnd - $dateStart;
    $fullDays = floor($dateDiff/(60*60*24));
    $fullHours = floor(($dateDiff-($fullDays*60*60*24))/(60*60));
    $fullMinutes = floor(($dateDiff-($fullDays*60*60*24)-($fullHours*60*60))/60);
    $displayStr = "";
    if( $fullDays > 1 ) {
        $displayStr .= $fullDays.' Tage ';
    }else if( $fullDays > 0 ) {
            $displayStr .= $fullDays.' Tag ';
        }
    if( $fullHours > 1 ) {
        $displayStr .= $fullHours.' Stunden ';
    }else if( $fullHours > 0 ) {
            $displayStr .= $fullHours.' Stunde ';
        }
    if( $fullMinutes > 1 ) {
        $displayStr .= $fullMinutes.' Minuten ';
    }else if( $fullMinutes > 0 ) {
            $displayStr .= $fullMinutes.' Minute ';
        }
    if( $displayStr == ""){
        $displayStr = "< 1 Minute";
    }
    return( $displayStr );
}


function xstats_displayMaxValue( $gameId, $colName ) {
    //contains player colors
    include ('../../inc.conf.php');
    $maxValue = xstats_getMaxValue( $gameId, $colName );
    $query = "SELECT * FROM skrupel_xstats WHERE gameid={$gameId} AND {$colName}={$maxValue}";
    $result = @mysql_query( $query );
    $result = @mysql_fetch_array($result);
    $playerId = $result['playerid'];
    $playerIndex = $result['playerindex'];
    $turn = $result['turn'];
    $displayStr = '<table class="shiptable" border="0"><tr><th width="25%">';
    if( $colName == 'shipcount' ) {
        $displayStr .= "Gr&ouml;&szlig;te Flotte (Gesamt):</th><td width=\"25%\"><strong>".$maxValue."</strong> Schiffe ";
    }else if( $colName == 'freightercount' ) {
            $displayStr .= "Gr&ouml;&szlig;te Flotte (Frachter):</th><td width=\"25%\"><strong>".$maxValue."</strong> Schiffe ";
        }else if( $colName == 'shipcount-freightercount' ) {
                $displayStr .= "Gr&ouml;&szlig;te Flotte (Bewaffnet):</th><td width=\"25%\"><strong>".$maxValue."</strong> Schiffe ";
            }else if( $colName == 'planetcount' ) {
                    $displayStr .= "Gr&ouml;&szlig;tes Imperium:</th><td width=\"25%\"><strong>".$maxValue."</strong> Planeten ";
                }else if( $colName == 'colonistcount' ) {
                        $displayStr .= "Gr&ouml;&szlig;te Bev&ouml;lkerung:</th><td width=\"25%\"><strong>".$maxValue."</strong> Kolonisten ";
                    }else if( $colName == 'cantoxcount' ) {
                            $displayStr .= "Gr&ouml;&szlig;ter Reichtum:</th><td width=\"25%\"><strong>".$maxValue."</strong> Cantox ";
                        }else if( $colName == 'lemincount' ) {
                                $displayStr .= "Gr&ouml;&szlig;ter Spritbesitz:</th><td width=\"25%\"><strong>".$maxValue."</strong> Lemin ";
                            }else if( $colName == 'factorycount' ) {
                                    $displayStr .= "Gr&ouml;&szlig;ter Fabrikbesitzer:</th><td width=\"25%\"><strong>".$maxValue."</strong> Fabriken ";
                                }else if( $colName == 'minescount' ) {
                                        $displayStr .= "Gr&ouml;&szlig;ter Minenbesitzer:</th><td width=\"25%\"><strong>".$maxValue."</strong> Minen ";
                                    }else if( $colName == 'sumcargohold' ) {
                                            $displayStr .= "Gr&ouml;&szlig;ter Frachtraum auf Frachtern:</th><td width=\"25%\"><strong>".$maxValue."</strong> KT ";
                                        }else if( $colName == 'lj' ) {
                                                $displayStr .= "Gr&ouml;&szlig;te Distanz geflogen:</th><td width=\"25%\"><strong>".$maxValue."</strong> Lj ";
                                            }
    $displayStr .= '</td><td width="50%">';
    $displayStr .= 'Erreicht durch <span style="color: ' . $spielerfarbe[$playerIndex] . ';"><strong>' . xstats_getPlayerNick($playerId) . '</strong></span> in Runde ' . $turn;
    $displayStr .= '</td></tr></table>';
    return $displayStr;
}


/**Returns a data array that should be displayed for a list of players*/
function xstats_displayMaxSum( $gameId, $colName, $maxTurn, $xstatsAvailablePlayerIndicies ) {
    include ('../../inc.conf.php');
    $maxValue = 0;
    $maxPlayerId = 0;
    $maxPlayerIndex = 0;
    foreach( $xstatsAvailablePlayerIndicies as $playerIndex ) {
        $computedValue = 0;
        $computedPlayerId = 0;
        $computedPlayerIndex = 0;
        for($currentTurn=1; $currentTurn<=$maxTurn; $currentTurn++) {
            $query = "SELECT {$colName},playerid FROM skrupel_xstats WHERE playerindex={$playerIndex} AND gameid={$gameId} AND turn={$currentTurn}";
            $result = @mysql_query($query) or die(mysql_error());
            $result = @mysql_fetch_array($result);
            $colNameResult = $result[$colName];
            if( !is_null( $colNameResult )) {
                $computedPlayerId = $result['playerid'];
                $computedPlayerIndex = $playerIndex;
                $computedValue+=$colNameResult;
            }
        }
        //new max value found
        if( $computedValue > $maxValue ) {
            $maxValue = $computedValue;
            $maxPlayerId = $computedPlayerId;
            $maxPlayerIndex = $computedPlayerIndex;
        }
    }
    if( $maxValue > 0 ) {
        $displayStr = '<table class="shiptable" border="0"><tr><th width="25%">';
        if( $colName == 'lj' ) {
            $displayStr .= "Gr&ouml;&szlig;te Gesamtdistanz:</th><td width=\"25%\"><strong>".$maxValue."</strong> Lichtjahre";
        }else if( $colName == 'battlecount' ) {
                $displayStr .= "An den meisten Raumk&auml;mpfen teilgenommen:</th><td width=\"25%\"><strong>".$maxValue."</strong> K&auml;mpfe";
            }else if( $colName == 'battlewoncount' ) {
                    $displayStr .= "Die meisten Raumk&auml;mpfe gewonnen:</th><td width=\"25%\"><strong>".$maxValue."</strong> K&auml;mpfe";
                }else if( $colName == 'battlecount-battlewoncount' ) {
                        $displayStr .= "Die meisten Raumk&auml;mpfe verloren:</th><td width=\"25%\"><strong>".$maxValue."</strong> K&auml;mpfe";
                    }else if( $colName == 'coloniestakencount' ) {
                            $displayStr .= "Die meisten Kolonien erobert:</th><td width=\"25%\"><strong>".$maxValue."</strong> Kolonien";
                        }
        $displayStr .= '</td><td width="50%">';
        $displayStr .= 'Erreicht durch <span style="color: '.$spielerfarbe[$maxPlayerIndex].';"><strong>'.xstats_getPlayerNick($maxPlayerId).'</strong></span>';
        $displayStr .= '</td></tr></table>';
        echo $displayStr;
    }
}


/**Displays the type of the game
 * *  0: Just for Fun
        * 1: Überleben
        * 2: Todfeind
        * 3: Dominanz (noch nicht implementiert)
        * 4: King of the Planet (noch nicht implementier)
        * 5: Spice
        * 6: Teamtodfeind
 */
function xstats_getGameType( $gameId ) {
    $result = @mysql_query("SELECT * FROM skrupel_spiele WHERE id='$gameId'") or die(mysql_error());
    $result = @mysql_fetch_array($result);
    if( $result['ziel_id'] == 0 ) {
        return( 'Just for fun');
    }else if( $result['ziel_id'] == 1 ) {
            return( '&Uuml;berleben');
        }else if( $result['ziel_id'] == 2 ) {
                return( 'Todfeind');
            }else if( $result['ziel_id'] == 3 ) {
                    return( 'Dominanz');
                }else if( $result['ziel_id'] == 4 ) {
                        return( 'King of the Planet');
                    }else if( $result['ziel_id'] == 5 ) {
                            return( 'Spice');
                        }else if( $result['ziel_id'] == 6 ) {
                                return( 'Teamtodfeind');
                            }
}

/**Displays the date of the first registered tick*/
function xstats_getGameStart( $gameId ) {
    $query = 'SELECT * FROM skrupel_xstats_turntime WHERE gameid='.$gameId.' AND turn=(SELECT MIN(turn) FROM skrupel_xstats_turntime WHERE gameid='.$gameId.')';
    $result = @mysql_query($query) or die(mysql_error());
    $result = @mysql_fetch_array($result);
    $turnendTime = $result['turnendtime'];
    return( date('d.m.Y H:i:s', $turnendTime));
}

/**Displays the date of the first registered tick*/
function xstats_getGameDuration( $gameId ) {
    $query = 'SELECT * FROM skrupel_xstats_turntime WHERE gameid='.$gameId.' AND turn=(SELECT MIN(turn) FROM skrupel_xstats_turntime WHERE gameid='.$gameId.')';
    $result = @mysql_query($query) or die(mysql_error());
    $result = @mysql_fetch_array($result);
    $minTime = $result['turnendtime'];
    $query = 'SELECT * FROM skrupel_xstats_turntime WHERE gameid='.$gameId.' AND turn=(SELECT MAX(turn) FROM skrupel_xstats_turntime WHERE gameid='.$gameId.')';
    $result = @mysql_query($query) or die(mysql_error());
    $result = @mysql_fetch_array($result);
    $maxTime = $result['turnendtime'];
    return( xstats_getDateDiff($minTime, $maxTime));
}


/**Displays the date of the last tick*/
function xstats_getGameEnd( $gameId ) {
    $query = 'SELECT * FROM skrupel_xstats_turntime WHERE gameid='.$gameId.' AND turn=(SELECT MAX(turn) FROM skrupel_xstats_turntime WHERE gameid='.$gameId.')';
    $result = @mysql_query($query) or die(mysql_error());
    $result = @mysql_fetch_array($result);
    $turnendTime = $result['turnendtime'];
    return( date('d.m.Y H:i:s', $turnendTime));
}


/**Displays the actual ranking for the passed game id*/
function xstats_displayRanking( $gameId ) {
    include ('../../inc.conf.php');
    echo( "<H3>Skrupelrang nach Spielende</H3>");
    $ranking = array();
    for($k=1; $k<=10; $k++) {
        $result = @mysql_query("SELECT * FROM skrupel_spiele WHERE id='$gameId'") or die(mysql_error());
        $result = @mysql_fetch_array($result);
        $playerId = $result['spieler_'.$k];
        $playerRank = $result['spieler_'.$k.'_platz'];
        if($playerId != 0) {
            $ranking[] = '<tr><td>'.
                '<strong>'.$playerRank.'. </strong>'.
                '<img src="../../daten/'.$result['spieler_'.$k.'_rasse'].'/bilder_allgemein/menu.png" height="18" class="beveled">'.
                ' <strong><font color="'.$spielerfarbe[$k].'"> '.
                xstats_getPlayerNick($playerId).'</font></strong></td><td>als '.$result['spieler_'.$k.'_rassename'].
                ':</td><td align="center">'.$result['spieler_'.$k.'_planeten'].'</td><td align="center">'.
                $result['spieler_'.$k.'_schiffe'].'</td><td align="center">'.
                $result['spieler_'.$k.'_basen'].'</td></tr>';
        }
    }
    sort( $ranking );
    echo( '<table border="0">');
    echo '<tr><td colspan="2"><img src="../../lang/de/topics/dieimperien.gif" width="140"></td>';
    echo '<td><img src="../../bilder/aufbau/rang_2.gif"></td>';
    echo '<td><img src="../../bilder/aufbau/rang_3.gif"></td>';
    echo '<td><img src="../../bilder/aufbau/rang_1.gif"></td>';
    echo '<td>';
    foreach( $ranking as $rankLine) {
        echo( $rankLine);
    }
    echo( '</table>');
}

/**Displays a list with all ships*/
function xstats_displayShipList( $gameId ) {
    $playerIndexList = xstats_getAvailablePlayerIndicies($gameId);
    foreach($playerIndexList as $playerIndex) {
        xstats_displayShipListOfUser( $gameId, $playerIndex);
    }
}

/**Returns the last owner index entry of a ship of a turn. Mainly this should be maxturn but if anything strange happened
 * with the colletion processing that could be a lower value. Mainly this is just a function to make the display more
 * fail safe
 */
function xstats_getLastShipOwnerIndexAtTurn( $gameId, $shipId ) {
    $query = "SELECT ownerindex FROM skrupel_xstats_shipowner WHERE gameid=".$gameId." AND shipid=".$shipId." ORDER BY turn DESC";
    $result = @mysql_query($query) or die(mysql_error());
    if( mysql_num_rows($result)>0 ) {
        $result = @mysql_fetch_array($result);
        return( $result['ownerindex']);
    }
}


/**Returns the owner index of a ship of a turn*/
function xstats_getShipOwnerIndexAtTurn( $gameId, $shipId, $turn ) {
    $query = "SELECT ownerindex FROM skrupel_xstats_shipowner WHERE gameid=".$gameId." AND shipid=".$shipId." AND turn=".$turn;
    $result = @mysql_query($query) or die(mysql_error());
    if( mysql_num_rows($result)>0 ) {
        $result = @mysql_fetch_array($result);
        return( $result['ownerindex']);
    }
}

/**Returns the owner id of a ship of a turn*/
function xstats_getShipOwnerIdAtTurn( $gameId, $shipId, $turn ) {
    $query = "SELECT ownerid FROM skrupel_xstats_shipowner WHERE gameid=".$gameId." AND shipid=".$shipId." AND turn=".$turn;
    $result = @mysql_query($query) or die(mysql_error());
    if( mysql_num_rows($result)>0 ) {
        $result = @mysql_fetch_array($result);
        return( $result['ownerid']);
    }
}

/**Returns the planet icon for a passed position and a passed game*/
function xstats_getPlanetDescription( $gameId, $posX, $posY, $ownerIndex, $planetName ) {
    include ('../../inc.conf.php');
    $query = "SELECT * FROM skrupel_planeten WHERE spiel=".$gameId." AND x_pos=".$posX." AND y_pos=".$posY;
    $result = @mysql_query($query) or die(mysql_error());
    //planet found?
    if( mysql_num_rows($result)>0 ) {
        $result = mysql_fetch_array($result);
        return( '<img src="../../bilder/planeten/'.$result['klasse'].'_'.$result['bild'].'.jpg" height="24" border="1" style="border:1px solid '.$spielerfarbe[$ownerIndex].'"> <span>'.$planetName.'</span>');
    }
    return( "" );
}

/**Displays a list with all ships of a user odererd by the rounds*/
function xstats_displayShipListOfUser( $gameId, $userIndex ) {
    $userId = xstats_getPlayerId($gameId, $userIndex);
    $maxTurn = xstats_getMaxTurn($gameId);
    include ('../../inc.conf.php');
    $query = "SELECT *FROM skrupel_xstats_ships ships INNER JOIN skrupel_xstats_shipowner shipowner ON (ships.shipid=shipowner.shipid AND ships.sinceturn=shipowner.turn AND ships.gameid=shipowner.gameid) WHERE shipowner.ownerindex=".$userIndex." AND ships.gameId=".$gameId." ORDER BY ships.sinceturn";
    $result = @mysql_query($query) or die(mysql_error());
    $maxFleet = xstats_getMaxValueOfUser($gameId, "shipcount", $userId);
    echo '<h3>Liste aller produzierten Schiffe von <font color="'.$spielerfarbe[$userIndex].'">'.xstats_getPlayerNick($userId).'</font></h3><h4>Gr&ouml;&szlig;te Flotte: '.$maxFleet.' Schiffe</h4>';
    echo '<table class="shiptable" border="0">';
    echo '<tr><th>Schiff</th><th>Von</th><th>Siege</th><th>In Betrieb</th><th>Masse</th><th>Antriebe</th><th>Laser</th><th>Torp</th><th>Hangar</th><th>Zerst&ouml;rt von</th></tr>';
    while ($row = mysql_fetch_array($result)) {
        echo '<tr>';
        //ship
        echo '<td>'.xstats_getShipFullDescription( $gameId, $row['shipid'], $row['shiprace'], $row['picturesmall'], $row['experience'], $row['sinceturn'],$row['shipclass'],$row['shipname']).'</td>';
        //production planet
        echo '<td>'.xstats_getPlanetDescription( $gameId, $row['buildposx'], $row['buildposy'], $userIndex, $row['buildplanetname']).'</td>';
        //victory count
        echo '<td>'.$row['victories'].'</td>';
        //from-to
        if( $row['untilturn'] == '0' || $row['untilturn'] == 0) {
            $untilTurn = $maxTurn;
        }else {
            $untilTurn = $row['untilturn'];
        }
        echo '<td>Runde '.$row['sinceturn'].'-'.$untilTurn.'</td>';
        //mass
        echo '<td>'.$row['mass'].' kT</td>';
        //engine
        $levelEngine = $row['levelengine'];
        if( $levelEngine == 8 ) {
            $levelEngine = 7;
        }
        echo '<td>'.$row['enginecount'].'* Lvl '.$levelEngine.'</td>';
        //laser
        if( $row['beamcount'] == 0 ) {
            echo( "<td>0</td>");
        }
        else {
            echo '<td>'.$row['beamcount'].'* Lvl '.$row['levelbeam'].'</td>';
        }
        //tubes
        if( $row['tubecount'] == 0 ) {
            echo( "<td>0</td>");
        }
        else {
            echo '<td>'.$row['tubecount'].'* Lvl '.$row['leveltube'].'</td>';
        }
        //hangar
        echo '<td>'.$row['hangarcount'].'</td>';
        //destroyed by
        $query = "SELECT * FROM skrupel_xstats_shipvsship WHERE shipid=".$row['shipid']." AND fightresult=2 AND gameid=".$gameId;
        $destroyerResult = @mysql_query( $query ) or die(mysql_error());
        if( mysql_num_rows($destroyerResult)>0 ) {
            $destroyerRow = mysql_fetch_array($destroyerResult);
            $query = "SELECT * FROM skrupel_xstats_ships WHERE gameId='".$gameId."' AND shipid=".$destroyerRow['enemyshipid'];
            $destroyerInfoResult = @mysql_query($query) or die(mysql_error());
            $destroyerInfoRow = mysql_fetch_array($destroyerInfoResult);
            echo '<td>'.xstats_getShipFullDescription( $gameId, $destroyerInfoRow['shipid'], $destroyerInfoRow['shiprace'], $destroyerInfoRow['picturesmall'], $destroyerInfoRow['experience'], $destroyerInfoRow['sinceturn'],$destroyerInfoRow['shipclass'],$destroyerInfoRow['shipname']).'</td>';
        }else {
        //not destroyed by a ship, destroyed by a planetary defense
            $query = "SELECT * FROM skrupel_xstats_shipvsplanet WHERE shipid=".$row['shipid']." AND eventtype=1 AND gameid=".$gameId;
            $destroyerResult = @mysql_query( $query ) or die(mysql_error());
            if( mysql_num_rows($destroyerResult)>0 ) {
                $destroyerInfoRow = mysql_fetch_array($destroyerResult);
                echo '<td>'.xstats_getPlanetDescription( $gameId, $destroyerInfoRow['posx'], $destroyerInfoRow['posy'], $destroyerInfoRow['planetownerindex'], $destroyerInfoRow['planetname']).' (Planetare Verteidigung)</td>';
            }else {
            //not destroyed
                echo '<td></td>';
            }
        }
        echo '<tr>';
    }
    echo '</table>';
}


/**Displays a single ship icon with experience
 */
function xstats_getShipFullDescription( $gameId, $shipId, $race, $picturesmall, $experience, $turn, $shipclass, $shipname) {
//could be 0 if the ship is not destroyed at the end of the game
    if( $turn == 0 || $turn == xstats_getMaxTurn($gameId)) {
        $ownerIndex = xstats_getLastShipOwnerIndexAtTurn($gameId, $shipId );
    }else {
        $ownerIndex = xstats_getShipOwnerIndexAtTurn($gameId, $shipId, $turn);
    }
    return( xstats_getShipIconWithExp( $race, $picturesmall, $experience, $ownerIndex ).' <span>'.$shipclass.' ['.$shipname.'_'.$shipId.']</span>' );
}

/**Displays a single ship icon with experience*/
function xstats_getShipIconWithExp( $race, $picturesmall, $experience, $ownerindex) {
    include ('../../inc.conf.php');
    return( xstats_getShipIcon( $race, $picturesmall, $ownerindex).'<img src="../../bilder/icons/erf_'.$experience.'.gif" class="padded" />' );
}

/**Displays a single ship icon*/
function xstats_getShipIcon( $race, $picturesmall, $ownerindex) {
    include ('../../inc.conf.php');
    return( '<img src="../../daten/'.$race.'/bilder_schiffe/'.$picturesmall.'" height="24" border="1" style="border:1px solid '.$spielerfarbe[$ownerindex].'">' );
}

/**Displays a list of fights of the ships*/
function xstats_displayShipFightsByShip( $gameId, $maxRows) {
    include ('../../inc.conf.php');
    $maxTurn = xstats_getMaxTurn($gameId);
    $query = "SELECT * FROM skrupel_xstats_ships WHERE gameid=".$gameId." AND victories > 0";
    $result = @mysql_query($query) or die(mysql_error());
    echo '<table class="shiptable" border="0">';
    echo '<tr><th>Schiff</th><th>Siege</th><th>In Betrieb</th><th>Antriebe</th><th>Laser</th><th>Torp</th><th>Hangar</th></tr>';
    while ($row = mysql_fetch_array($result)) {
    //dont display ships without victory
        if( $row['victories'] == 0 ) {
            break;
        }
        echo '<tr>';
        //ship
        echo '<td>'.xstats_getShipFullDescription( $gameId, $row['shipid'], $row['shiprace'], $row['picturesmall'], $row['experience'], $row['untilturn'], $row['shipclass'], $row['shipname']).'</td>';
        //victory count
        echo '<td>'.$row['victories'].'</td>';
        //from-to
        if( $row['untilturn'] == '0' || $row['untilturn'] == 0) {
            $untilTurn = $maxTurn;
        }else {
            $untilTurn = $row['untilturn'];
        }
        echo '<td class="highlight">Runde '.$row['sinceturn'].'-'.$untilTurn.'</td>';
        //engine
        $levelEngine = $row['levelengine'];
        if( $levelEngine == 8 ) {
            $levelEngine = 7;
        }
        echo '<td>'.$row['enginecount'].'* Lvl '.$levelEngine.'</td>';
        //laser
        if( $row['beamcount'] == 0 ) {
            echo( "<td>0</td>");
        }
        else {
            echo '<td>'.$row['beamcount'].'* Lvl '.$row['levelbeam'].'</td>';
        }
        //tubes
        if( $row['tubecount'] == 0 ) {
            echo( "<td>0</td>");
        }
        else {
            echo '<td>'.$row['tubecount'].'* Lvl '.$row['leveltube'].'</td>';
        }
        //hangar
        echo '<td>'.$row['hangarcount'].'</td>';
        echo '</tr>';
        $query = "SELECT * FROM skrupel_xstats_ships ships,skrupel_xstats_shipvsship shipvsship WHERE shipvsship.shipid=ships.shipid AND (shipvsship.fightresult=2 OR shipvsship.fightresult=3) AND enemyshipid=".$row['shipid']." AND shipvsship.gameid=".$gameId." AND ships.gameid=".$gameId." ORDER BY turn";
        $victoryResult = @mysql_query( $query ) or die(mysql_error());
        while ($victoryRow = mysql_fetch_array($victoryResult)) {
            echo "<tr>";
            echo "<td></td>";
            echo '<td colspan="6">';
            if( $victoryRow['fightresult'] == 2) {
                echo 'Zerst&ouml;rt ';
                $usedTurn = $victoryRow['turn'];
            }else {
                echo 'Erobert ';
                $usedTurn = $victoryRow['turn']-1;
            }
            echo xstats_getShipFullDescription( $gameId, $victoryRow['shipid'], $victoryRow['shiprace'], $victoryRow['picturesmall'], $victoryRow['experience'], $usedTurn, $victoryRow['shipclass'],$victoryRow['shipname']);
            echo ' in Runde '.$victoryRow['turn'];
            echo '</td>';
            echo "</tr>";
        }
        //find out who captured the ship
        $query = "SELECT * FROM skrupel_xstats_shipvsship WHERE shipid=".$row['shipid']." AND fightresult=3 AND gameid=".$gameId;
        $captureResult = @mysql_query( $query ) or die(mysql_error());
        if( mysql_num_rows($captureResult)>0 ) {
            while($captureRow = mysql_fetch_array($captureResult)) {
                $captureInfoResult = @mysql_query("SELECT * FROM skrupel_xstats_ships WHERE gameId='".$gameId."' AND shipid=".$captureRow['enemyshipid']) or die(mysql_error());
                $captureInfoRow = mysql_fetch_array($captureInfoResult);
                echo "<tr>";
                echo "<td></td>";
                echo '<td colspan="6">';
                echo 'Wurde erobert von '.xstats_getShipFullDescription( $gameId, $captureInfoRow['shipid'], $captureInfoRow['shiprace'], $captureInfoRow['picturesmall'], $captureInfoRow['experience'], $captureInfoRow['turn'],$captureInfoRow['shipclass'],$captureInfoRow['shipname']);
                echo ' in Runde '.$captureRow['turn'];
                echo '</td>';
                echo '</tr>';
            }
        }
        //find out who destroyed the ship finally
        $query = "SELECT * FROM skrupel_xstats_shipvsship WHERE shipid=".$row['shipid']." AND fightresult=2 AND gameid=".$gameId;
        $destroyerResult = @mysql_query( $query ) or die(mysql_error());
        if( mysql_num_rows($destroyerResult)>0 ) {
            $destroyerRow = mysql_fetch_array($destroyerResult);
            $destroyerInfoResult = @mysql_query("SELECT * FROM skrupel_xstats_ships WHERE gameId='".$gameId."' AND shipid=".$destroyerRow['enemyshipid']) or die(mysql_error());
            $destroyerInfoRow = mysql_fetch_array($destroyerInfoResult);
            echo "<tr>";
            echo "<td></td>";
            echo '<td colspan="6">';
            echo 'Wurde zerst&ouml;rt von '.xstats_getShipFullDescription( $gameId, $destroyerInfoRow['shipid'], $destroyerInfoRow['shiprace'], $destroyerInfoRow['picturesmall'], $destroyerInfoRow['experience'], $destroyerRow['turn'],$destroyerInfoRow['shipclass'],$destroyerInfoRow['shipname']);
            echo ' in Runde '.$destroyerRow['turn'];
            echo '</td>';
            echo '</tr>';
        }else {
        //perhaps destroyed by planetary defense?
            $query = "SELECT * FROM skrupel_xstats_shipvsplanet WHERE shipid=".$row['shipid']." AND eventtype=1 AND gameid=".$gameId;
            $destroyerInfoResult = @mysql_query( $query ) or die(mysql_error());
            if( mysql_num_rows($destroyerInfoResult)>0 ) {
                $destroyerInfoRow = mysql_fetch_array($destroyerInfoResult);
                echo "<tr>";
                echo "<td></td>";
                echo '<td colspan="6">';
                echo 'Wurde zerst&ouml;rt von '.xstats_getPlanetDescription( $gameId, $destroyerInfoRow['posx'], $destroyerInfoRow['posy'], $destroyerInfoRow['planetownerindex'], $row['buildplanetname']).' (Planetare Verteidigung)';
                echo ' in Runde '.$destroyerRow['turn'];
                echo '</td>';
                echo '</tr>';
            }
        }
    }
    echo '</table>';
}

/**Displays all fights of the game*/
function xstats_displayAllFights( $gameId ) {
    include ('../../inc.conf.php');
    $query = "SELECT * FROM skrupel_xstats_ships ships,skrupel_xstats_shipvsship shipvsship WHERE shipvsship.shipid=ships.shipid AND (shipvsship.fightresult=2 OR shipvsship.fightresult=3) AND shipvsship.gameid=".$gameId." AND ships.gameid=".$gameId." ORDER BY turn,shipvsship.id";
    $result = @mysql_query( $query ) or die(mysql_error());
    echo '<table class="shiptable" border="0">';
    echo '<tr><th>Runde</th><th colspan="3">Kampf</th><th>H&uuml;llenschaden</tr>';
    while ($row = mysql_fetch_array($result)) {
        echo "<tr>";
        //turn
        echo '<td class="highlight">'.$row['turn'].'</td>';
        echo '<td>';
        //get victorous ship
        $query = "SELECT * FROM skrupel_xstats_ships WHERE gameid=".$gameId." AND shipid=".$row['enemyshipid'];
        $victoryResult = @mysql_query( $query ) or die(mysql_error());
        $victoryRow = mysql_fetch_array($victoryResult);
        echo xstats_getShipFullDescription( $gameId, $victoryRow['shipid'], $victoryRow['shiprace'], $victoryRow['picturesmall'], $victoryRow['experience'], $row['turn'],$victoryRow['shipclass'],$victoryRow['shipname']);
        echo '</td><td>';
        if( $row['fightresult'] == 2) {
            $turnToUse = $row['turn'];
            echo ' zerst&ouml;rt ';
        }else {
            echo ' erobert ';
            //display the formerly owner of this ship
            $turnToUse = $row['turn']-1;
        }
        echo '</td><td>';
        echo xstats_getShipFullDescription( $gameId, $row['shipid'], $row['shiprace'], $row['picturesmall'], $row['experience'], $turnToUse,$row['shipclass'],$row['shipname']);
        echo '</td>';
        //get hull damage of winning ship
        $query = "SELECT * FROM skrupel_xstats_shipvsship WHERE shipid=".$row['enemyshipid']." AND enemyshipid=".$row['shipid']." AND gameid=".$gameId;
        $winnerResult = @mysql_query( $query ) or die(mysql_error());
        $winnerResult = mysql_fetch_array($winnerResult);
        $hullDamage = $winnerResult['hulldamage'];
        echo '<td>'.$hullDamage.'%';
        //hull damage bar
        echo '<div class="hulldamage">';
        echo '<div style="width: '.(100-$hullDamage).'%"></div>';
        echo '</div>';
        echo '</td>';
        echo "</tr>";
    }
    echo '</table>';
}

/**Displays a list of ships sorted by the exp col*/
function xstats_displayShipsExpBattleships( $gameId, $maxRows) {
    include ('../../inc.conf.php');
    $maxTurn = xstats_getMaxTurn($gameId);
    $result = @mysql_query("SELECT * FROM skrupel_xstats_ships WHERE gameId='".$gameId."' AND(beamcount>0 OR hangarcount>0 OR tubecount>0) ORDER BY experience DESC") or die(mysql_error());
    echo '<table class="shiptable" border="0">';
    echo '<tr><th>Schiff</th><th>Siege</th><th>Herstellungsort</th><th>In Betrieb</th></tr>';
    $counter = 0;
    while ($counter++ < $maxRows && $row = mysql_fetch_array($result)) {
        if( $row['untilturn'] == '0' || $row['untilturn'] == 0) {
            $untilTurn = $maxTurn;
        }else {
            $untilTurn = $row['untilturn'];
        }
        echo '<tr>';
        //ship
        echo '<td>'.xstats_getShipFullDescription( $gameId, $row['shipid'], $row['shiprace'], $row['picturesmall'], $row['experience'], $untilTurn,$row['shipclass'],$row['shipname']).'</td>';
        //victories
        echo '<td>'.$row['victories'].'</td>';
        //home planet
        $planetOwnerIndex = xstats_getShipOwnerIndexAtTurn($gameId, $row['shipid'], $row['sinceturn']);
        echo '<td>'.xstats_getPlanetDescription( $gameId, $row['buildposx'], $row['buildposy'], $planetOwnerIndex, $row['buildplanetname'] ).'</td>';
        //from-to
        echo '<td>Runde '.$row['sinceturn'].'-'.$untilTurn.'</td>';
        echo '</tr>';
    }
    echo '</table>';
}

/**Displays a list of ships sorted by the exp col*/
function xstats_displayShipsExpFreighter( $gameId, $maxRows) {
    include ('../../inc.conf.php');
    $maxTurn = xstats_getMaxTurn($gameId);
    $result = @mysql_query("SELECT * FROM skrupel_xstats_ships WHERE gameId='".$gameId."' AND beamcount=0 AND hangarcount=0 AND tubecount=0 ORDER BY experience DESC") or die(mysql_error());
    echo '<table class="shiptable" border="0">';
    echo '<tr><th>Schiff</th><th>Herstellungsort</th><th>In Betrieb</th></tr>';
    $counter = 0;
    while ($counter++ < $maxRows && $row = mysql_fetch_array($result)) {
        if( $row['untilturn'] == '0' || $row['untilturn'] == 0) {
            $untilTurn = $maxTurn;
        }else {
            $untilTurn = $row['untilturn'];
        }
        echo '<tr>';
        //ship
        echo '<td>'.xstats_getShipFullDescription( $gameId, $row['shipid'], $row['shiprace'], $row['picturesmall'], $row['experience'], $untilTurn,$row['shipclass'],$row['shipname']).'</td>';
        //home planet
        $planetOwnerIndex = xstats_getShipOwnerIndexAtTurn($gameId, $row['shipid'], $row['sinceturn']);
        echo '<td>'.xstats_getPlanetDescription( $gameId, $row['buildposx'], $row['buildposy'], $planetOwnerIndex, $row['buildplanetname'] ).'</td>';
        //from-to
        echo '<td>Runde '.$row['sinceturn'].'-'.$untilTurn.'</td>';
        echo '</tr>';
    }
    echo '</table>';
}

/**Displays a list of ships with most cargo and without any weapons*/
function xstats_displayFreigtherMostCargo( $gameId, $maxRows ) {
    include ('../../inc.conf.php');
    $maxTurn = xstats_getMaxTurn($gameId);
    $query = "SELECT * FROM skrupel_xstats_ships WHERE gameId='".$gameId."' AND tubecount=0 AND beamcount=0 AND hangarcount=0 ORDER BY cargosum DESC";
    $result = @mysql_query($query) or die(mysql_error());
    echo '<table class="shiptable" border="0">';
    echo '<tr><th>Schiff</th><th>Frachtraum/kT</th><th>Gesamtfracht/kT</th><th>Auslastung</th><th>In Betrieb</th></tr>';
    $cargoSumTransportedMax = -1;
    $counter = 0;
    while ($counter++ < $maxRows && $row = mysql_fetch_array($result)) {
        if( $row['untilturn'] == '0' || $row['untilturn'] == 0) {
            $untilTurn = $maxTurn;
        }else {
            $untilTurn = $row['untilturn'];
        }
        echo '<tr>';
        //ship
        echo '<td>'.xstats_getShipFullDescription( $gameId, $row['shipid'], $row['shiprace'], $row['picturesmall'], $row['experience'], $row['untilturn'],$row['shipclass'],$row['shipname']).'</td>';
        //cargo hold
        echo '<td>'.$row['cargomax'].'</td>';
        //cargo sum transported
        if( $cargoSumTransportedMax == -1 ) {
            $cargoSumTransportedMax = $row['cargosum'];
        }
        echo '<td class="highlight">';
        echo '<div class="percentbar">';
        $cargoPercent = $row['cargosum']*100/$cargoSumTransportedMax;
        echo '<div style="width: '.$cargoPercent.'%"></div>';
        echo '</div>';
        echo $row['cargosum'];
        echo '</td>';
        //cargo efficiency
        $efficiency = ($row['cargosum']*100)/(($untilTurn-$row['sinceturn'])*$row['cargomax']);
        $efficiency = number_format($efficiency,1);
        echo '<td class="highlight"><img src="../extend/xstats/pie.php?perc='.$efficiency.'&size=30" /><span>'.$efficiency.'%</span></td>';
        //from-to
        echo '<td>Runde '.$row['sinceturn'].'-'.$untilTurn.'</td>';
        echo '</tr>';
    }
    echo '</table>';
}

/**Displays a list of ships sorted by the distance col*/
function xstats_displayShipMaxLJ( $gameId, $maxRows ) {
    include ('../../inc.conf.php');
    $maxTurn = xstats_getMaxTurn($gameId);
    $result = @mysql_query("SELECT * FROM skrupel_xstats_ships WHERE gameId='".$gameId."' ORDER BY lj DESC") or die(mysql_error());
    echo '<table class="shiptable" border="0">';
    echo '<tr><th>Schiff</th><th>Strecke</th><th>Herstellungsort</th><th>In Betrieb</th></tr>';
    $maxDistance = -1;
    $counter = 0;
    while ($counter++ < $maxRows && $row = mysql_fetch_array($result)) {
        if( $row['untilturn'] == '0' || $row['untilturn'] == 0) {
            $untilTurn = $maxTurn;
        }else {
            $untilTurn = $row['untilturn'];
        }
        echo '<tr>';
        //ship
        echo '<td>'.xstats_getShipFullDescription( $gameId, $row['shipid'], $row['shiprace'], $row['picturesmall'], $row['experience'], $untilTurn, $row['shipclass'],$row['shipname']).'</td>';
        //distance
        //first value is max distance
        if( $maxDistance == -1 ) {
            $maxDistance = $row['lj'];
        }
        echo '<td class="highlight">';
        echo '<div class="percentbar">';
        $distancePercent = $row['lj']*100/$maxDistance;
        echo '<div style="width: '.$distancePercent.'%"></div>';
        echo '</div>';
        echo $row['lj'].' Lj';
        echo '</td>';
        //home planet, this is the planet where the ship occured first
        $planetOwnerIndex = xstats_getShipOwnerIndexAtTurn($gameId, $row['shipid'], $row['sinceturn']);
        echo '<td>'.xstats_getPlanetDescription( $gameId, $row['buildposx'], $row['buildposy'], $planetOwnerIndex, $row['buildplanetname'] ).'</td>';
        //from-to
        echo '<td>Runde '.$row['sinceturn'].'-'.$untilTurn.'</td>';
        echo '</tr>';
    }
    echo '</table>';
}

/**Checks for the most popular ships in game and displays this*/
function xstats_displayShipProduction( $gameId, $numberOfRows) {
    $query = "SELECT DISTINCT(ownerid) FROM skrupel_xstats_shipowner WHERE gameId=".$gameId;
    $shipBuilderArray = array();
    $result = @mysql_query($query) or die(mysql_error());
    while($row = @mysql_fetch_row($result)) {
        $shipBuilderArray[] = $row[0];
    }
    foreach( $shipBuilderArray as $shipBuilderId) {
        xstats_displayShipProductionOfBuilder( $gameId, $shipBuilderId, $numberOfRows );
    }
}


/**Checks for the most popular ships in game and displays this*/
function xstats_displayShipProductionOfBuilder( $gameId, $shipBuilderId, $numberOfRows ) {
    include ('../../inc.conf.php');
    $shipBuilderIndex = xstats_getPlayerIndex($gameId, $shipBuilderId);
    $query = "SELECT DISTINCT(shipclassid) FROM skrupel_xstats_ships ships INNER JOIN skrupel_xstats_shipowner shipowner ON (ships.shipid=shipowner.shipid AND ships.sinceturn=shipowner.turn AND ships.gameid=shipowner.gameid) WHERE shipowner.ownerid=".$shipBuilderId." AND ships.gameId=".$gameId." ";
    $result = @mysql_query($query) or die(mysql_error());
    $shipClassArray = array();
    while($row = @mysql_fetch_row($result)) {
        $shipClassArray[] = $row[0];
    }
    $shipClassCountArray = array();
    foreach( $shipClassArray as $shipClassId) {
        $query = "SELECT COUNT(shipclassid) FROM skrupel_xstats_ships ships INNER JOIN skrupel_xstats_shipowner shipowner ON (ships.shipid=shipowner.shipid AND ships.sinceturn=shipowner.turn AND ships.gameid=shipowner.gameid) WHERE shipowner.ownerid=".$shipBuilderId." AND ships.gameId=".$gameId." AND shipclassid=".$shipClassId;
        $result = @mysql_query($query) or die(mysql_error());
        while($row = @mysql_fetch_row($result)) {
            $shipClassCountArray[$shipClassId] = $row[0];
        }
    }
    //get number of all built ships of this builder
    $query = "SELECT COUNT(1) FROM skrupel_xstats_ships ships INNER JOIN skrupel_xstats_shipowner shipowner ON (ships.shipid=shipowner.shipid AND ships.sinceturn=shipowner.turn AND ships.gameid=shipowner.gameid) WHERE shipowner.ownerid=".$shipBuilderId." AND ships.gameId=".$gameId;
    $result = @mysql_query($query) or die(mysql_error());
    $result = @mysql_fetch_row($result);
    $numberOfShipsProduced = $result[0];
    $shipClassArray = array();
    echo( '<h4>Gebaute Schiffstypen von <font color="'.$spielerfarbe[$shipBuilderIndex].'"> '.xstats_getPlayerNick($shipBuilderId).'</font> (Gesamtproduktion: '.$numberOfShipsProduced.' Schiffe)</h4>');
    echo '<table class="shiptable"border="0">';
    echo '<tr><th>Schiff</th><th>Anzahl</th><th>Anteil an Produktion</th><th>Tech Level</th><th>Masse</th><th>Frachtraum</th></tr>';
    arsort($shipClassCountArray);
    $shipClassArray = array_keys($shipClassCountArray);
    for( $i = 0; $i < count( $shipClassArray ); $i++ ) {
        if( $i+1 > $numberOfRows) {
            break;
        }
        $classId = $shipClassArray[$i];
        $classIdCount = $shipClassCountArray[$shipClassArray[$i]];
        //get one of the stats lines
        $query = "SELECT * FROM skrupel_xstats_ships ships INNER JOIN skrupel_xstats_shipowner shipowner ON (ships.shipid=shipowner.shipid AND ships.sinceturn=shipowner.turn AND ships.gameid=shipowner.gameid) WHERE shipowner.ownerid=".$shipBuilderId." AND ships.gameId=".$gameId." AND shipclassid=".$classId;
        $result = @mysql_query($query) or die(mysql_error());
        $result = @mysql_fetch_array($result);
        //ship description
        echo '<td>'.xstats_getShipIcon( $result['shiprace'], $result['picturesmall'], $shipBuilderIndex).' '.$result['shipclass'].'</td>';
        //abs count
        echo '<td class="highlight">'.$classIdCount.'</td>';
        //perc count
        $perc = number_format((100*$classIdCount/$numberOfShipsProduced),1);
        echo '<td class="highlight"><img src="../extend/xstats/pie.php?perc='.$perc.'&size=30"><span>'.$perc.'%</span></td>';
        //tech level of the hull
        echo '<td>'.$result['levelhull'].'</td>';
        //mass
        echo '<td>'.$result['mass'].' kT</td>';
        //cargo
        echo '<td>'.$result['cargomax'].' kT</td>';
        echo '<tr>';
    }
    echo '</table>';
}

/**Displays a list of max values of this game*/
function xstats_displayMaxValueListShips($gameId) {
    $statsAvailablePlayerIndicies = xstats_getAvailablePlayerIndicies($gameId);
    $statsMaxTurn = xstats_getMaxTurn($gameId);
    echo xstats_displayMaxSum( $gameId, 'lj', $statsMaxTurn, &$statsAvailablePlayerIndicies );
    echo xstats_displayMaxValue( $gameId, 'shipcount');
    echo xstats_displayMaxValue( $gameId, 'freightercount');
    echo xstats_displayMaxValue( $gameId, 'shipcount-freightercount');
    echo xstats_displayMaxValue( $gameId, 'sumcargohold');
}

/**Displays a list of max values of this game*/
function xstats_displayMaxValueShipVSShip($gameId) {
    $statsAvailablePlayerIndicies = xstats_getAvailablePlayerIndicies($gameId);
    $statsMaxTurn = xstats_getMaxTurn($gameId);
    echo xstats_displayMaxSum( $gameId, 'battlecount', $statsMaxTurn, &$statsAvailablePlayerIndicies );
    echo xstats_displayMaxSum( $gameId, 'battlewoncount', $statsMaxTurn, &$statsAvailablePlayerIndicies );
    echo xstats_displayMaxSum( $gameId, 'battlecount-battlewoncount', $statsMaxTurn, &$statsAvailablePlayerIndicies );
}


/**Displays a list of max values of this game*/
function xstats_displayMaxValueListMisc($gameId) {
    $statsAvailablePlayerIndicies = xstats_getAvailablePlayerIndicies($gameId);
    $statsMaxTurn = xstats_getMaxTurn($gameId);
    echo xstats_displayMaxSum( $gameId, 'coloniestakencount', $statsMaxTurn, &$statsAvailablePlayerIndicies );
    echo xstats_displayMaxValue( $gameId, 'planetcount');
    echo xstats_displayMaxValue( $gameId, 'colonistcount');
    echo xstats_displayMaxValue( $gameId, 'cantoxcount');
    echo xstats_displayMaxValue( $gameId, 'lemincount');
    echo xstats_displayMaxValue( $gameId, 'factorycount');
    echo xstats_displayMaxValue( $gameId, 'minescount');
    xstats_displayMaxWaitTime( $gameId );
}


?>
